masterdata/src/routes/web.php
<?php 
use Illuminate\Support\Facades\Route;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestCategoryController;
use Pondit\Ptrace\Masterdata\Http\Controllers\ReportGroupController;
use Pondit\Ptrace\Masterdata\Http\Controllers\TestTypeController;
use Pondit\Ptrace\Masterdata\Http\Controllers\TestMethodController;
use Pondit\Ptrace\Masterdata\Http\Controllers\SpecimenController;
use Pondit\Ptrace\Masterdata\Http\Controllers\CollectionRoomController;
use Pondit\Ptrace\Masterdata\Http\Controllers\EquipmentController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestOptionalItemController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestPreparationController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestController;
use Pondit\Ptrace\Masterdata\Http\Controllers\ReferenceController;
use Pondit\Ptrace\Masterdata\Http\Controllers\CareOfController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MarketingController;

use Pondit\Ptrace\Masterdata\Http\Controllers\OrganizationController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('medical-test-categories', MedicalTestCategoryController::class);
	Route::resource('report-groups', ReportGroupController::class);
	Route::resource('test-types', TestTypeController::class);
	Route::resource('test-methods', TestMethodController::class);
	Route::resource('specimens', SpecimenController::class);
	Route::resource('collection-rooms', CollectionRoomController::class);
	Route::resource('equipments', EquipmentController::class);
	Route::resource('medical-test-optional-items', MedicalTestOptionalItemController::class);
	Route::resource('medical-test-preparations', MedicalTestPreparationController::class);
	Route::resource('medical-tests', MedicalTestController::class);
	Route::resource('references', ReferenceController::class);
	Route::resource('care-ofs', CareOfController::class);
	Route::resource('marketings', MarketingController::class);
	Route::resource('organizations', OrganizationController::class);
//Place your route here
});

masterdata/src/Models/Reference.php
<?php

namespace Pondit\Ptrace\Masterdata\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\UserTrackable;
use App\Traits\RecordSequenceable;

use App\Traits\Historiable;

class Reference extends Model
{
    use UserTrackable;
    use SoftDeletes;
    use RecordSequenceable;
    
    use Historiable;
    protected $connection = 'masterdata';
    protected $table = 'references';
    protected $guarded = ['id'];
    

    /**
    * Get the route key for the model.
    *
    * @return string
    */
    public function getRouteKeyName()
    {
        return 'uuid';
    }
    
    ##ELOQUENTRELATIONSHIPMODEL##
}

masterdata/src/Http/Controllers/Api/ReferenceController.php
<?php
namespace Pondit\Ptrace\Masterdata\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Pondit\Ptrace\Masterdata\Models\Reference;
use Illuminate\Database\QueryException;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
//use another classes

class ReferenceController extends Controller
{

    /*
    |--------------------------------------------------------------------------
    | Response status code
    |--------------------------------------------------------------------------
    | 201 response with created data
    | 200 update/list/show/delete
    | 204 deleted response with no content
    | 500 internal server or db error
    */

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        $references = Reference::latest()->get();

        return response()->json([
            'status' => true,
            'data' => $references
        ], 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        try {
            $reference = Reference::create(['uuid'=> Str::uuid()] + $request->all());
            //handle relationship store
            return response()->json([
                'status' => true,
                'message' => __('Successfully Created'),
                'data' => $reference
            ], 201);
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return response()->json([
                'error' => config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Reference  $reference
     * @return \Illuminate\Http\JsonResponse
     */
    public function show(Reference $reference)
    {
         return response()->json([
            'status' => true,
            'data' => $reference
         ], 200);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Request  $request
     * @param  \App\Models\Reference  $reference
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, Reference $reference)
    {
        try {
            $reference->update($request->all());
            //handle relationship update
            return response()->json([
                'status' => true,
                'message' => __('Successfully Updated'),
                'data' => $reference
            ], 200);
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return response()->json([
                'error' => config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Reference  $reference
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Reference $reference)
    {
        try {
            $reference->delete();

            return response()->json([
                'status' => true,
                'message' => __('Successfully Deleted')
            ], 200);
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
             return response()->json([
                'error' => config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            ], 500);
        }
    }

//another methods
}

masterdata/src/Http/Controllers/ReferenceController.php
<?php

namespace Pondit\Ptrace\Masterdata\Http\Controllers;

use App\Http\Controllers\Controller;
use Pondit\Ptrace\Masterdata\Http\Requests\ReferenceRequest;
use Pondit\Ptrace\Masterdata\Models\Reference;
use Illuminate\Database\QueryException;
use Illuminate\Support\Str;
//use another classes

class ReferenceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('masterdata::references.index', [
                        'references' => Reference::latest()->get()
                     ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('masterdata::references.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\ReferenceRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ReferenceRequest $request)
    {
        try {
            $reference = Reference::create(['uuid'=> Str::uuid()] + $request->all());
            //handle relationship store
            return redirect()->route('references.index')
                ->withSuccess(__('Successfully Created'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Reference  $reference
     * @return \Illuminate\Http\Response
     */
    public function show(Reference $reference)
    {
        return view('masterdata::references.show', compact('reference'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Reference  $reference
     * @return \Illuminate\Http\Response
     */
    public function edit(Reference $reference)
    {
        return view('masterdata::references.edit', compact('reference'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\ReferenceRequest  $request
     * @param  \App\Models\Reference  $reference
     * @return \Illuminate\Http\Response
     */
    public function update(ReferenceRequest $request, Reference $reference)
    {
        try {
            $reference->update($request->all());
            //handle relationship update
            return redirect()->route('references.index')
                ->withSuccess(__('Successfully Updated'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Reference  $reference
     * @return \Illuminate\Http\Response
     */
    public function destroy(Reference $reference)
    {
        try {
            $reference->delete();

            return redirect()->route('references.index')
                ->withSuccess(__('Successfully Deleted'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

//another methods
}

masterdata/src/resources/views/references/create.blade.php
<x-masterdata-master>
	<x-utilities.card>
		<x-slot name="heading">
			{{ __('Reference') }}
		</x-slot>
		<x-slot name="body">
			<x-alerts.errors :errors="$errors" />
			<form action="{{ route('references.store') }}" method="POST">
				@csrf
				{{--relationalFields--}}
				<!-- discount_percent -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="discount_percentInput" :value="__('Discount Percentage')" />

					<x-forms.input type="number" class="form-control" id="discount_percentInput" name="discount_percent" :value="old('discount_percent')" placeholder="Discount Percentage" />

					<x-forms.error name="discount_percent" />
				</div>
				<!-- discount_value -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="discount_valueInput" :value="__('Discount Value')" />

					<x-forms.input type="number" class="form-control" id="discount_valueInput" name="discount_value" :value="old('discount_value')" placeholder="Discount Value" />

					<x-forms.error name="discount_value" />
				</div>
				<!-- is_suggested -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="is_suggestedInput" :value="__('Suggested')" /><br>
					<input class="form-check-input" type="radio" name="is_suggested" value="1" />Yes
					<input class="form-check-input" type="radio" name="is_suggested" value="0" /> No
					<x-forms.error name="is_suggested" />
				</div>

				<!-- special_price -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="special_priceInput" :value="__('Special Price')" />

					<x-forms.input type="number" class="form-control" id="special_priceInput" name="special_price" :value="old('special_price')" placeholder="Special Price" />

					<x-forms.error name="special_price" />
				</div>
				<!-- commission_percent -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="commission_percentInput" :value="__('Commission Percentage')" />

					<x-forms.input type="number" class="form-control" id="commission_percentInput" name="commission_percent" :value="old('commission_percent')" placeholder="Commission Percentage" />

					<x-forms.error name="commission_percent" />
				</div>
				<!-- commission_value -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="commission_valueInput" :value="__('Commission Value')" />

					<x-forms.input type="number" class="form-control" id="commission_valueInput" name="commission_value" :value="old('commission_value')" placeholder="Commission Value" />

					<x-forms.error name="commission_value" />
				</div>
				<!-- code -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="codeInput" :value="__('Code')" />

					<x-forms.input type="text" class="form-control" id="codeInput" name="code" :value="old('code')" placeholder="Code" />

					<x-forms.error name="code" />
				</div>
				<!-- reference_type -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="reference_typeInput" :value="__('Reference Type')" />

					<x-forms.input type="text" class="form-control" id="reference_typeInput" name="reference_type" :value="old('reference_type')" placeholder="Reference Type" />

					<x-forms.error name="reference_type" />
				</div>
				<!-- last_name -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="last_nameInput" :value="__('Last Name')" />

					<x-forms.input type="text" class="form-control" id="last_nameInput" name="last_name" :value="old('last_name')" placeholder="Last Name" />

					<x-forms.error name="last_name" />
				</div>
				<!-- first_name -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="first_nameInput" :value="__('First Name')" />

					<x-forms.input type="text" class="form-control" id="first_nameInput" name="first_name" :value="old('first_name')" placeholder="First Name" />

					<x-forms.error name="first_name" />
				</div>
				<!-- salutation -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="salutationInput" :value="__('Salutation')" />

					<x-forms.input type="text" class="form-control" id="salutationInput" name="salutation" :value="old('salutation')" placeholder="Salutation" />

					<x-forms.error name="salutation" />
				</div>

				<x-forms.button class="btn btn-info" type="submit">{{ __('Submit') }}</x-forms.button>
			</form>
		</x-slot>
		<x-slot name="footer" class="d-flex">
			<div></div>
			<div>
				<x-utilities.link-list href="{{route('references.index')}}"><i class="fa fa-list"></i> {{ __('List') }}</x-utilities.link-list>
			</div>
			<div></div>
		</x-slot>
	</x-utilities.card>

	@push('css')
	{{--pagespecific-css--}}
	@endpush

	@push('js')
	{{--pagespecific-js--}}
	@endpush

</x-masterdata-master>

masterdata/src/resources/views/references/edit.blade.php
<x-masterdata-master>
	<x-utilities.card>
		<x-slot name="heading">
			{{ __('Reference') }}
		</x-slot>
		<x-slot name="body">
			<x-alerts.errors :errors="$errors" />
			<form action="{{ route('references.update', $reference->uuid) }}" method="POST">
				@csrf
				@method('PATCH')
				{{--relationalFields--}}
				<!-- discount_percent -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="discount_percentInput" :value="__('Discount Percentage')" />

					<x-forms.input type="number" class="form-control" id="discount_percentInput" name="discount_percent" :value="old('discount_percent', $reference->discount_percent)" placeholder="Discount Percentage" />

					<x-forms.error name="discount_percent" />
				</div>
				<!-- discount_value -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="discount_valueInput" :value="__('Discount Value')" />

					<x-forms.input type="number" class="form-control" id="discount_valueInput" name="discount_value" :value="old('discount_value', $reference->discount_value)" placeholder="Discount Value" />

					<x-forms.error name="discount_value" />
				</div>
				<!-- is_suggested -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="is_suggestedInput" :value="__('Suggested')" /><br>
					<input class="form-check-input" type="radio" name="is_suggested" value="1" />Yes
					<input class="form-check-input" type="radio" name="is_suggested" value="0" /> No
					<x-forms.error name="is_suggested" />
				</div>
				<!-- special_price -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="special_priceInput" :value="__('Special Price')" />

					<x-forms.input type="number" class="form-control" id="special_priceInput" name="special_price" :value="old('special_price', $reference->special_price)" placeholder="Special Price" />

					<x-forms.error name="special_price" />
				</div>
				<!-- commission_percent -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="commission_percentInput" :value="__('Commission Percentage')" />

					<x-forms.input type="number" class="form-control" id="commission_percentInput" name="commission_percent" :value="old('commission_percent', $reference->commission_percent)" placeholder="Commission Percentage" />

					<x-forms.error name="commission_percent" />
				</div>
				<!-- commission_value -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="commission_valueInput" :value="__('Commission Value')" />

					<x-forms.input type="number" class="form-control" id="commission_valueInput" name="commission_value" :value="old('commission_value', $reference->commission_value)" placeholder="Commission Value" />

					<x-forms.error name="commission_value" />
				</div>
				<!-- code -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="codeInput" :value="__('Code')" />

					<x-forms.input type="text" class="form-control" id="codeInput" name="code" :value="old('code', $reference->code)" placeholder="Code" />

					<x-forms.error name="code" />
				</div>
				<!-- reference_type -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="reference_typeInput" :value="__('Reference Type')" />

					<x-forms.input type="text" class="form-control" id="reference_typeInput" name="reference_type" :value="old('reference_type', $reference->reference_type)" placeholder="Reference Type" />

					<x-forms.error name="reference_type" />
				</div>
				<!-- last_name -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="last_nameInput" :value="__('Last Name')" />

					<x-forms.input type="text" class="form-control" id="last_nameInput" name="last_name" :value="old('last_name', $reference->last_name)" placeholder="Last Name" />

					<x-forms.error name="last_name" />
				</div>
				<!-- first_name -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="first_nameInput" :value="__('First Name')" />

					<x-forms.input type="text" class="form-control" id="first_nameInput" name="first_name" :value="old('first_name', $reference->first_name)" placeholder="First Name" />

					<x-forms.error name="first_name" />
				</div>
				<!-- salutation -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="salutationInput" :value="__('Salutation')" />

					<x-forms.input type="text" class="form-control" id="salutationInput" name="salutation" :value="old('salutation', $reference->salutation)" placeholder="Salutation" />

					<x-forms.error name="salutation" />
				</div>

				<x-forms.button class="btn-primary" type="submit">{{ __('Submit') }}</x-forms.button>
			</form>
		</x-slot>
		<x-slot name="footer" class="d-flex">
			<div></div>
			<div>
				<x-utilities.link-list href="{{route('references.index')}}"><i class="fa fa-list"></i> {{ __('List') }}</x-utilities.link-list>
			</div>
			<div></div>
		</x-slot>
	</x-utilities.card>

	@push('css')
	{{--pagespecific-css--}}
	@endpush

	@push('js')
	{{--pagespecific-js--}}
	@endpush

</x-masterdata-master>

masterdata/src/resources/views/references/index.blade.php
<x-masterdata-master>
    <x-utilities.card>
        <x-slot name="heading">
            {{ __('Reference') }}
        </x-slot>
        <x-slot name="body">
            <x-alerts.message :message="session('success')" />
            <x-utilities.table-basic id="referenceDatatable" class="display responsive nowrap" style="width:100%">
                <x-utilities.table-basic-head class="bg-info">
                    <tr>
                        <th>{{ __('SL') }}</th>
						<th>{{ __('Discount Percentage') }}</th>
						<th>{{ __('Discount Value') }}</th>
						<th>{{ __('Suggested') }}</th>
						<th>{{ __('Special Price') }}</th>
						<th>{{ __('Commission Percentage') }}</th>
						<th>{{ __('Commission Value') }}</th>
						<th>{{ __('Code') }}</th>
						<th>{{ __('Reference Type') }}</th>
						<th>{{ __('Last Name') }}</th>
						<th>{{ __('First Name') }}</th>
						<th>{{ __('Salutation') }}</th>

                        <th>{{ __('Actions' )}}</th>
                    </tr>
                </x-utilities.table-basic-head>
                <x-utilities.table-basic-body>
                    @foreach ($references as $reference)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
						<td>{{ $reference->discount_percent }}</td>
						<td>{{ $reference->discount_value }}</td>
						<td>{{ $reference->is_suggested }}</td>
						<td>{{ $reference->special_price }}</td>
						<td>{{ $reference->commission_percent }}</td>
						<td>{{ $reference->commission_value }}</td>
						<td>{{ $reference->code }}</td>
						<td>{{ $reference->reference_type }}</td>
						<td>{{ $reference->last_name }}</td>
						<td>{{ $reference->first_name }}</td>
						<td>{{ $reference->salutation }}</td>

                        <td class="d-flex justify-content-center">
                            <x-utilities.link-show href="{{route('references.show', $reference->uuid)}}">{{ __('Show') }}</x-utilities.link-show>
                        
                            <x-utilities.link-edit href="{{route('references.edit', $reference->uuid)}}">{{ __('Edit') }}</x-utilities.link-edit>
                        
                            <form style="display:inline" action="{{route('references.destroy', $reference->uuid)}}" method="post">
                            @csrf
                            @method('delete')
                                <x-forms.button class="btn btn-danger" onClick="return confirm('Are you sure want to delete ?')" type="submit">{{ __('Delete') }}</x-forms.button> 
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </x-utilities.table-basic-body>
            </x-utilities.table-basic>
        </x-slot>
        <x-slot name="footer" class="d-flex">
			<div></div>
			<div>
				<x-utilities.link-create href="{{route('references.create')}}"><i class="fa fa-plus"></i> {{ __('Add New') }}</x-utilities.link-create>
			</div>
			<div></div>
		</x-slot>
    </x-utilities.card>

@push('css')
{{--pagespecific-css--}}
<link href="{{ asset('ui') }}/css/jquery.dataTables.min.css" rel="stylesheet" >
<link href="{{ asset('ui') }}/css/responsive.dataTables.min.css" rel="stylesheet" >
<link href="{{ asset('ui') }}/css/buttons.dataTables.min.css" rel="stylesheet" >
@endpush

@push('js')
{{--pagespecific-js--}}
<script src="ui/js/jquery.dataTables.min.js"></script>
<script src="ui/js/dataTables.responsive.min.js"></script>
<script src="ui/js/dataTables.buttons.min.js"></script>
<script src="ui/js/buttons.colVis.min.js"></script>

<script>
   $(document).ready(function() {
    $('#referenceDatatable').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'colvis'
        ]
    } );
  } );
</script>
@endpush

</x-masterdata-master>

masterdata/src/resources/views/references/show.blade.php
<x-masterdata-master>
    <x-utilities.card>
        <x-slot name="heading">
            {{ __('Reference') }}
        </x-slot>
        <x-slot name="body">
            <p><b>{{ __('Discount Percentage') }} : </b> {{ $reference->discount_percent }}</p>
			<p><b>{{ __('Discount Value') }} : </b> {{ $reference->discount_value }}</p>
			<p><b>{{ __('Suggested') }} : </b> {{ $reference->is_suggested }}</p>
			<p><b>{{ __('Special Price') }} : </b> {{ $reference->special_price }}</p>
			<p><b>{{ __('Commission Percentage') }} : </b> {{ $reference->commission_percent }}</p>
			<p><b>{{ __('Commission Value') }} : </b> {{ $reference->commission_value }}</p>
			<p><b>{{ __('Code') }} : </b> {{ $reference->code }}</p>
			<p><b>{{ __('Reference Type') }} : </b> {{ $reference->reference_type }}</p>
			<p><b>{{ __('Last Name') }} : </b> {{ $reference->last_name }}</p>
			<p><b>{{ __('First Name') }} : </b> {{ $reference->first_name }}</p>
			<p><b>{{ __('Salutation') }} : </b> {{ $reference->salutation }}</p>
			
            {{--othersInfo--}}
        </x-slot>
        <x-slot name="footer" class="d-flex">
			<div></div>
			<div>
				<x-utilities.link-list href="{{route('references.index')}}"><i class="fa fa-list"></i> {{ __('List') }}</x-utilities.link-list>
			</div>
			<div></div>
		</x-slot>
    </x-utilities.card>
    
@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush
</x-masterdata-master>