masterdata/src/routes/web.php
<?php 
use Illuminate\Support\Facades\Route;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestCategoryController;
use Pondit\Ptrace\Masterdata\Http\Controllers\ReportGroupController;
use Pondit\Ptrace\Masterdata\Http\Controllers\TestTypeController;
use Pondit\Ptrace\Masterdata\Http\Controllers\TestMethodController;
use Pondit\Ptrace\Masterdata\Http\Controllers\SpecimenController;
use Pondit\Ptrace\Masterdata\Http\Controllers\CollectionRoomController;
use Pondit\Ptrace\Masterdata\Http\Controllers\EquipmentController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestOptionalItemController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestPreparationController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestController;
use Pondit\Ptrace\Masterdata\Http\Controllers\ReferenceController;
use Pondit\Ptrace\Masterdata\Http\Controllers\CareOfController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MarketingController;

use Pondit\Ptrace\Masterdata\Http\Controllers\OrganizationController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('medical-test-categories', MedicalTestCategoryController::class);
	Route::resource('report-groups', ReportGroupController::class);
	Route::resource('test-types', TestTypeController::class);
	Route::resource('test-methods', TestMethodController::class);
	Route::resource('specimens', SpecimenController::class);
	Route::resource('collection-rooms', CollectionRoomController::class);
	Route::resource('equipments', EquipmentController::class);
	Route::resource('medical-test-optional-items', MedicalTestOptionalItemController::class);
	Route::resource('medical-test-preparations', MedicalTestPreparationController::class);
	Route::resource('medical-tests', MedicalTestController::class);
	Route::resource('references', ReferenceController::class);
	Route::resource('care-ofs', CareOfController::class);
	Route::resource('marketings', MarketingController::class);
	Route::resource('organizations', OrganizationController::class);
//Place your route here
});

masterdata/src/Models/ReportGroup.php
<?php

namespace Pondit\Ptrace\Masterdata\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\UserTrackable;
use App\Traits\RecordSequenceable;

use App\Traits\Historiable;

class ReportGroup extends Model
{
    use UserTrackable;
    use SoftDeletes;
    use RecordSequenceable;
    
    use Historiable;
    protected $connection = 'masterdata';
    protected $table = 'report_groups';
    protected $guarded = ['id'];
    

    /**
    * Get the route key for the model.
    *
    * @return string
    */
    public function getRouteKeyName()
    {
        return 'uuid';
    }
    
    public function medicalTests()
    {
        return $this->hasMany(\Pondit\Ptrace\Masterdata\Models\MedicalTest::class);
    }

    ##ELOQUENTRELATIONSHIPMODEL##
}

masterdata/src/Http/Controllers/Api/ReportGroupController.php
<?php
namespace Pondit\Ptrace\Masterdata\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Pondit\Ptrace\Masterdata\Models\ReportGroup;
use Illuminate\Database\QueryException;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
//use another classes

class ReportGroupController extends Controller
{

    /*
    |--------------------------------------------------------------------------
    | Response status code
    |--------------------------------------------------------------------------
    | 201 response with created data
    | 200 update/list/show/delete
    | 204 deleted response with no content
    | 500 internal server or db error
    */

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        $reportGroups = ReportGroup::latest()->get();

        return response()->json([
            'status' => true,
            'data' => $reportGroups
        ], 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        try {
            $reportGroup = ReportGroup::create(['uuid'=> Str::uuid()] + $request->all());
            //handle relationship store
            return response()->json([
                'status' => true,
                'message' => __('Successfully Created'),
                'data' => $reportGroup
            ], 201);
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return response()->json([
                'error' => config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ReportGroup  $reportGroup
     * @return \Illuminate\Http\JsonResponse
     */
    public function show(ReportGroup $reportGroup)
    {
         return response()->json([
            'status' => true,
            'data' => $reportGroup
         ], 200);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Request  $request
     * @param  \App\Models\ReportGroup  $reportGroup
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, ReportGroup $reportGroup)
    {
        try {
            $reportGroup->update($request->all());
            //handle relationship update
            return response()->json([
                'status' => true,
                'message' => __('Successfully Updated'),
                'data' => $reportGroup
            ], 200);
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return response()->json([
                'error' => config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ReportGroup  $reportGroup
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(ReportGroup $reportGroup)
    {
        try {
            $reportGroup->delete();

            return response()->json([
                'status' => true,
                'message' => __('Successfully Deleted')
            ], 200);
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
             return response()->json([
                'error' => config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            ], 500);
        }
    }

//another methods
}

masterdata/src/Http/Controllers/ReportGroupController.php
<?php

namespace Pondit\Ptrace\Masterdata\Http\Controllers;

use App\Http\Controllers\Controller;
use Pondit\Ptrace\Masterdata\Http\Requests\ReportGroupRequest;
use Pondit\Ptrace\Masterdata\Models\ReportGroup;
use Illuminate\Database\QueryException;
use Illuminate\Support\Str;
//use another classes

class ReportGroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('masterdata::report-groups.index', [
                        'reportGroups' => ReportGroup::latest()->get()
                     ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('masterdata::report-groups.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\ReportGroupRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ReportGroupRequest $request)
    {
        try {
            $reportGroup = ReportGroup::create(['uuid'=> Str::uuid()] + $request->all());
            //handle relationship store
            return redirect()->route('report-groups.index')
                ->withSuccess(__('Successfully Created'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ReportGroup  $reportGroup
     * @return \Illuminate\Http\Response
     */
    public function show(ReportGroup $reportGroup)
    {
        return view('masterdata::report-groups.show', compact('reportGroup'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ReportGroup  $reportGroup
     * @return \Illuminate\Http\Response
     */
    public function edit(ReportGroup $reportGroup)
    {
        return view('masterdata::report-groups.edit', compact('reportGroup'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\ReportGroupRequest  $request
     * @param  \App\Models\ReportGroup  $reportGroup
     * @return \Illuminate\Http\Response
     */
    public function update(ReportGroupRequest $request, ReportGroup $reportGroup)
    {
        try {
            $reportGroup->update($request->all());
            //handle relationship update
            return redirect()->route('report-groups.index')
                ->withSuccess(__('Successfully Updated'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ReportGroup  $reportGroup
     * @return \Illuminate\Http\Response
     */
    public function destroy(ReportGroup $reportGroup)
    {
        try {
            $reportGroup->delete();

            return redirect()->route('report-groups.index')
                ->withSuccess(__('Successfully Deleted'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

//another methods
}

masterdata/src/resources/views/report-groups/create.blade.php
<x-masterdata-master>
    <x-utilities.card>
        <x-slot name="heading">
            {{ __('Report Group') }}
        </x-slot>
        <x-slot name="body">
            <x-alerts.errors :errors="$errors" />
            <form action="{{ route('report-groups.store') }}" method="POST">
                @csrf
                {{--relationalFields--}}
                                <!-- title -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="titleInput" :value="__('Report Group Title')" />

					<x-forms.input type="text" class="form-control" id="titleInput" name="title" :value="old('title')" placeholder="Report Group Title" />

				   <x-forms.error name="title" />
				</div>

                <x-forms.button class="btn btn-info" type="submit">{{ __('Submit') }}</x-forms.button> 
            </form>
        </x-slot>
        <x-slot name="footer" class="d-flex">
			<div></div>
			<div>
				<x-utilities.link-list href="{{route('report-groups.index')}}"><i class="fa fa-list"></i> {{ __('List') }}</x-utilities.link-list>
			</div>
			<div></div>
		</x-slot>
    </x-utilities.card>
    
@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush
    
</x-masterdata-master>

masterdata/src/resources/views/report-groups/edit.blade.php
<x-masterdata-master>
    <x-utilities.card>
        <x-slot name="heading">
            {{ __('Report Group') }}
        </x-slot>
        <x-slot name="body">
            <x-alerts.errors :errors="$errors" />
            <form action="{{ route('report-groups.update', $reportGroup->uuid) }}" method="POST">
                @csrf
                @method('PATCH')
                {{--relationalFields--}}
                                <!-- title -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="titleInput" :value="__('Report Group Title')" />

					<x-forms.input type="text" class="form-control" id="titleInput" name="title" :value="old('title', $reportGroup->title)" placeholder="Report Group Title" />

				   <x-forms.error name="title" />
				</div>

                <x-forms.button class="btn-primary" type="submit">{{ __('Submit') }}</x-forms.button> 
            </form>
        </x-slot>
        <x-slot name="footer" class="d-flex">
			<div></div>
			<div>
				<x-utilities.link-list href="{{route('report-groups.index')}}"><i class="fa fa-list"></i> {{ __('List') }}</x-utilities.link-list>
			</div>
			<div></div>
		</x-slot>
    </x-utilities.card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-masterdata-master>

masterdata/src/resources/views/report-groups/index.blade.php
<x-masterdata-master>
    <x-utilities.card>
        <x-slot name="heading">
            {{ __('Report Group') }}
        </x-slot>
        <x-slot name="body">
            <x-alerts.message :message="session('success')" />
            <x-utilities.table-basic id="reportGroupDatatable" class="display responsive nowrap" style="width:100%">
                <x-utilities.table-basic-head class="bg-info">
                    <tr>
                        <th>{{ __('SL') }}</th>
						<th>{{ __('Report Group Title') }}</th>

                        <th>{{ __('Actions' )}}</th>
                    </tr>
                </x-utilities.table-basic-head>
                <x-utilities.table-basic-body>
                    @foreach ($reportGroups as $reportGroup)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
						<td>{{ $reportGroup->title }}</td>

                        <td class="d-flex justify-content-center">
                            <x-utilities.link-show href="{{route('report-groups.show', $reportGroup->uuid)}}">{{ __('Show') }}</x-utilities.link-show>
                        
                            <x-utilities.link-edit href="{{route('report-groups.edit', $reportGroup->uuid)}}">{{ __('Edit') }}</x-utilities.link-edit>
                        
                            <form style="display:inline" action="{{route('report-groups.destroy', $reportGroup->uuid)}}" method="post">
                            @csrf
                            @method('delete')
                                <x-forms.button class="btn btn-danger" onClick="return confirm('Are you sure want to delete ?')" type="submit">{{ __('Delete') }}</x-forms.button> 
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </x-utilities.table-basic-body>
            </x-utilities.table-basic>
        </x-slot>
        <x-slot name="footer" class="d-flex">
			<div></div>
			<div>
				<x-utilities.link-create href="{{route('report-groups.create')}}"><i class="fa fa-plus"></i> {{ __('Add New') }}</x-utilities.link-create>
			</div>
			<div></div>
		</x-slot>
    </x-utilities.card>

@push('css')
{{--pagespecific-css--}}
<link href="{{ asset('ui') }}/css/jquery.dataTables.min.css" rel="stylesheet" >
<link href="{{ asset('ui') }}/css/responsive.dataTables.min.css" rel="stylesheet" >
<link href="{{ asset('ui') }}/css/buttons.dataTables.min.css" rel="stylesheet" >
@endpush

@push('js')
{{--pagespecific-js--}}
<script src="ui/js/jquery.dataTables.min.js"></script>
<script src="ui/js/dataTables.responsive.min.js"></script>
<script src="ui/js/dataTables.buttons.min.js"></script>
<script src="ui/js/buttons.colVis.min.js"></script>

<script>
   $(document).ready(function() {
    $('#reportGroupDatatable').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'colvis'
        ]
    } );
  } );
</script>
@endpush

</x-masterdata-master>

masterdata/src/resources/views/report-groups/show.blade.php
<x-masterdata-master>
    <x-utilities.card>
        <x-slot name="heading">
            {{ __('Report Group') }}
        </x-slot>
        <x-slot name="body">
            <p><b>{{ __('Report Group Title') }} : </b> {{ $reportGroup->title }}</p>
			
            @if(count($reportGroup->medicalTests))
<h3>{{ __('Medical Test') }}</h3>
<table class="table">
    <thead>
        <tr>
        <th>{{ __('Equipment Quantity') }}</th>
<th>{{ __('Equipment wise Quantity Total Price') }}</th>
<th>{{ __('Quantity Available') }}</th>
<th>{{ __('Doctor Required') }}</th>
<th>{{ __('Minimum Discount Percent') }}</th>
<th>{{ __('Minimum Discount Value') }}</th>
<th>{{ __('Discount Available') }}</th>
<th>{{ __('Traveller Price') }}</th>
<th>{{ __('Special Price') }}</th>
<th>{{ __('Price') }}</th>
<th>{{ __('Profit Margine') }}</th>
<th>{{ __('Service Charge') }}</th>
<th>{{ __('Others Commission') }}</th>
<th>{{ __('Marketing Commission') }}</th>
<th>{{ __('Doctor Commission') }}</th>
<th>{{ __('Others Cost') }}</th>
<th>{{ __('Lab Cost') }}</th>
<th>{{ __('Reagent Cost') }}</th>
<th>{{ __('Base Cost') }}</th>
<th>{{ __('Maximum Testing Time') }}</th>
<th>{{ __('Minimum Testing Time') }}</th>
<th>{{ __('Description') }}</th>
<th>{{ __('Title') }}</th>

        </tr>
    </thead>
    <tbody>
    @foreach($reportGroup->medicalTests as $medicalTest)<tr><td>{{ $medicalTest->equipment_quantity }}</td>
<td>{{ $medicalTest->equipment_wise_total_price }}</td>
<td>{{ $medicalTest->is_quantity_editable }}</td>
<td>{{ $medicalTest->is_doctor_required }}</td>
<td>{{ $medicalTest->max_discount_percent }}</td>
<td>{{ $medicalTest->min_discount_value }}</td>
<td>{{ $medicalTest->is_discount_avilable }}</td>
<td>{{ $medicalTest->traveller_price }}</td>
<td>{{ $medicalTest->special_price }}</td>
<td>{{ $medicalTest->price }}</td>
<td>{{ $medicalTest->margine }}</td>
<td>{{ $medicalTest->service_charge }}</td>
<td>{{ $medicalTest->other_commission }}</td>
<td>{{ $medicalTest->marketing_commission }}</td>
<td>{{ $medicalTest->doctor_commission }}</td>
<td>{{ $medicalTest->other_cost }}</td>
<td>{{ $medicalTest->lab_cost }}</td>
<td>{{ $medicalTest->reagent_cost }}</td>
<td>{{ $medicalTest->base_cost }}</td>
<td>{{ $medicalTest->max_testing_time }}</td>
<td>{{ $medicalTest->min_testing_time }}</td>
<td>{{ $medicalTest->description }}</td>
<td>{{ $medicalTest->title }}</td>
</tr>
@endforeach
    </tbody>
</table>
@endif
			{{--othersInfo--}}
        </x-slot>
        <x-slot name="footer" class="d-flex">
			<div></div>
			<div>
				<x-utilities.link-list href="{{route('report-groups.index')}}"><i class="fa fa-list"></i> {{ __('List') }}</x-utilities.link-list>
			</div>
			<div></div>
		</x-slot>
    </x-utilities.card>
    
@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush
</x-masterdata-master>