masterdata/src/routes/web.php
<?php 
use Illuminate\Support\Facades\Route;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestCategoryController;
use Pondit\Ptrace\Masterdata\Http\Controllers\ReportGroupController;
use Pondit\Ptrace\Masterdata\Http\Controllers\TestTypeController;
use Pondit\Ptrace\Masterdata\Http\Controllers\TestMethodController;
use Pondit\Ptrace\Masterdata\Http\Controllers\SpecimenController;
use Pondit\Ptrace\Masterdata\Http\Controllers\CollectionRoomController;
use Pondit\Ptrace\Masterdata\Http\Controllers\EquipmentController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestOptionalItemController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestPreparationController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MedicalTestController;
use Pondit\Ptrace\Masterdata\Http\Controllers\ReferenceController;
use Pondit\Ptrace\Masterdata\Http\Controllers\CareOfController;
use Pondit\Ptrace\Masterdata\Http\Controllers\MarketingController;

use Pondit\Ptrace\Masterdata\Http\Controllers\OrganizationController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('medical-test-categories', MedicalTestCategoryController::class);
	Route::resource('report-groups', ReportGroupController::class);
	Route::resource('test-types', TestTypeController::class);
	Route::resource('test-methods', TestMethodController::class);
	Route::resource('specimens', SpecimenController::class);
	Route::resource('collection-rooms', CollectionRoomController::class);
	Route::resource('equipments', EquipmentController::class);
	Route::resource('medical-test-optional-items', MedicalTestOptionalItemController::class);
	Route::resource('medical-test-preparations', MedicalTestPreparationController::class);
	Route::resource('medical-tests', MedicalTestController::class);
	Route::resource('references', ReferenceController::class);
	Route::resource('care-ofs', CareOfController::class);
	Route::resource('marketings', MarketingController::class);
	Route::resource('organizations', OrganizationController::class);
//Place your route here
});

masterdata/src/Models/CareOf.php
<?php

namespace Pondit\Ptrace\Masterdata\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\UserTrackable;
use App\Traits\RecordSequenceable;

use App\Traits\Historiable;

class CareOf extends Model
{
    use UserTrackable;
    use SoftDeletes;
    use RecordSequenceable;
    
    use Historiable;
    protected $connection = 'masterdata';
    protected $table = 'care_ofs';
    protected $guarded = ['id'];
    

    /**
    * Get the route key for the model.
    *
    * @return string
    */
    public function getRouteKeyName()
    {
        return 'uuid';
    }
    
    ##ELOQUENTRELATIONSHIPMODEL##
}

masterdata/src/Http/Controllers/Api/CareOfController.php
<?php
namespace Pondit\Ptrace\Masterdata\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Pondit\Ptrace\Masterdata\Models\CareOf;
use Illuminate\Database\QueryException;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
//use another classes

class CareOfController extends Controller
{

    /*
    |--------------------------------------------------------------------------
    | Response status code
    |--------------------------------------------------------------------------
    | 201 response with created data
    | 200 update/list/show/delete
    | 204 deleted response with no content
    | 500 internal server or db error
    */

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        $careOfs = CareOf::latest()->get();

        return response()->json([
            'status' => true,
            'data' => $careOfs
        ], 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        try {
            $careOf = CareOf::create(['uuid'=> Str::uuid()] + $request->all());
            //handle relationship store
            return response()->json([
                'status' => true,
                'message' => __('Successfully Created'),
                'data' => $careOf
            ], 201);
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return response()->json([
                'error' => config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\CareOf  $careOf
     * @return \Illuminate\Http\JsonResponse
     */
    public function show(CareOf $careOf)
    {
         return response()->json([
            'status' => true,
            'data' => $careOf
         ], 200);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Request  $request
     * @param  \App\Models\CareOf  $careOf
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, CareOf $careOf)
    {
        try {
            $careOf->update($request->all());
            //handle relationship update
            return response()->json([
                'status' => true,
                'message' => __('Successfully Updated'),
                'data' => $careOf
            ], 200);
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return response()->json([
                'error' => config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\CareOf  $careOf
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(CareOf $careOf)
    {
        try {
            $careOf->delete();

            return response()->json([
                'status' => true,
                'message' => __('Successfully Deleted')
            ], 200);
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
             return response()->json([
                'error' => config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            ], 500);
        }
    }

//another methods
}

masterdata/src/Http/Controllers/CareOfController.php
<?php

namespace Pondit\Ptrace\Masterdata\Http\Controllers;

use App\Http\Controllers\Controller;
use Pondit\Ptrace\Masterdata\Http\Requests\CareOfRequest;
use Pondit\Ptrace\Masterdata\Models\CareOf;
use Illuminate\Database\QueryException;
use Illuminate\Support\Str;
//use another classes

class CareOfController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('masterdata::care-ofs.index', [
                        'careOfs' => CareOf::latest()->get()
                     ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('masterdata::care-ofs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CareOfRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CareOfRequest $request)
    {
        try {
            $careOf = CareOf::create(['uuid'=> Str::uuid()] + $request->all());
            //handle relationship store
            return redirect()->route('care-ofs.index')
                ->withSuccess(__('Successfully Created'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\CareOf  $careOf
     * @return \Illuminate\Http\Response
     */
    public function show(CareOf $careOf)
    {
        return view('masterdata::care-ofs.show', compact('careOf'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\CareOf  $careOf
     * @return \Illuminate\Http\Response
     */
    public function edit(CareOf $careOf)
    {
        return view('masterdata::care-ofs.edit', compact('careOf'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\CareOfRequest  $request
     * @param  \App\Models\CareOf  $careOf
     * @return \Illuminate\Http\Response
     */
    public function update(CareOfRequest $request, CareOf $careOf)
    {
        try {
            $careOf->update($request->all());
            //handle relationship update
            return redirect()->route('care-ofs.index')
                ->withSuccess(__('Successfully Updated'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\CareOf  $careOf
     * @return \Illuminate\Http\Response
     */
    public function destroy(CareOf $careOf)
    {
        try {
            $careOf->delete();

            return redirect()->route('care-ofs.index')
                ->withSuccess(__('Successfully Deleted'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

//another methods
}

masterdata/src/resources/views/care-ofs/create.blade.php
<x-masterdata-master>
	<x-utilities.card>
		<x-slot name="heading">
			{{ __('Care Of') }}
		</x-slot>
		<x-slot name="body">
			<x-alerts.errors :errors="$errors" />
			<form action="{{ route('care-ofs.store') }}" method="POST">
				@csrf
				{{--relationalFields--}}

				<!-- care_name -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="care_nameInput" :value="__('Care Name')" />

					<x-forms.input type="text" class="form-control" id="care_nameInput" name="care_name" :value="old('care_name')" placeholder="Care Name" />

					<x-forms.error name="care_name" />
				</div>
				<!-- code -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="codeInput" :value="__('Code')" />

					<x-forms.input type="text" class="form-control" id="codeInput" name="code" :value="old('code')" placeholder="Code" />

					<x-forms.error name="code" />
				</div>

				<!-- service_charge -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="service_chargeInput" :value="__('Service Charge')" />

					<x-forms.input type="number" class="form-control" id="service_chargeInput" name="service_charge" :value="old('service_charge')" placeholder="Service Charge" />

					<x-forms.error name="service_charge" />
				</div>


				<!-- discount_percent -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="discount_percentInput" :value="__('Discount Percent')" />

					<x-forms.input type="number" class="form-control" id="discount_percentInput" name="discount_percent" :value="old('discount_percent')" placeholder="Discount Percent" />

					<x-forms.error name="discount_percent" />
				</div>

				<!-- discount_amount -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="discount_amountInput" :value="__('Discount Amount')" />

					<x-forms.input type="number" class="form-control" id="discount_amountInput" name="discount_amount" :value="old('discount_amount')" placeholder="Discount Amount" />

					<x-forms.error name="discount_amount" />
				</div>


				<x-forms.button class="btn btn-info" type="submit">{{ __('Submit') }}</x-forms.button>
			</form>
		</x-slot>
		<x-slot name="footer" class="d-flex">
			<div></div>
			<div>
				<x-utilities.link-list href="{{route('care-ofs.index')}}"><i class="fa fa-list"></i> {{ __('List') }}</x-utilities.link-list>
			</div>
			<div></div>
		</x-slot>
	</x-utilities.card>

	@push('css')
	{{--pagespecific-css--}}
	@endpush

	@push('js')
	{{--pagespecific-js--}}
	@endpush

</x-masterdata-master>

masterdata/src/resources/views/care-ofs/edit.blade.php
<x-masterdata-master>
	<x-utilities.card>
		<x-slot name="heading">
			{{ __('Care Of') }}
		</x-slot>
		<x-slot name="body">
			<x-alerts.errors :errors="$errors" />
			<form action="{{ route('care-ofs.update', $careOf->uuid) }}" method="POST">
				@csrf
				@method('PATCH')
				{{--relationalFields--}}

				<!-- care_name -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="care_nameInput" :value="__('Care Name')" />

					<x-forms.input type="text" class="form-control" id="care_nameInput" name="care_name" :value="old('care_name', $careOf->care_name)" placeholder="Care Name" />

					<x-forms.error name="care_name" />
				</div>


				<!-- code -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="codeInput" :value="__('Code')" />

					<x-forms.input type="text" class="form-control" id="codeInput" name="code" :value="old('code', $careOf->code)" placeholder="Code" />

					<x-forms.error name="code" />
				</div>


				<!-- service_charge -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="service_chargeInput" :value="__('Service Charge')" />

					<x-forms.input type="number" class="form-control" id="service_chargeInput" name="service_charge" :value="old('service_charge', $careOf->service_charge)" placeholder="Service Charge" />

					<x-forms.error name="service_charge" />
				</div>


				<!-- discount_percent -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="discount_percentInput" :value="__('Discount Percent')" />

					<x-forms.input type="number" class="form-control" id="discount_percentInput" name="discount_percent" :value="old('discount_percent', $careOf->discount_percent)" placeholder="Discount Percent" />

					<x-forms.error name="discount_percent" />
				</div>


				<x-forms.button class="btn-primary" type="submit">{{ __('Submit') }}</x-forms.button>
			</form>
		</x-slot>
		<x-slot name="footer" class="d-flex">
			<div></div>
			<div>

				<!-- discount_amount -->
				<div class="mb-3">
					<x-forms.label class="form-label" for="discount_amountInput" :value="__('Discount Amount')" />

					<x-forms.input type="number" class="form-control" id="discount_amountInput" name="discount_amount" :value="old('discount_amount', $careOf->discount_amount)" placeholder="Discount Amount" />

					<x-forms.error name="discount_amount" />
				</div>

				<x-utilities.link-list href="{{route('care-ofs.index')}}"><i class="fa fa-list"></i> {{ __('List') }}</x-utilities.link-list>
			</div>
			<div></div>
		</x-slot>
	</x-utilities.card>

	@push('css')
	{{--pagespecific-css--}}
	@endpush

	@push('js')
	{{--pagespecific-js--}}
	@endpush

</x-masterdata-master>

masterdata/src/resources/views/care-ofs/index.blade.php
<x-masterdata-master>
    <x-utilities.card>
        <x-slot name="heading">
            {{ __('Care Of') }}
        </x-slot>
        <x-slot name="body">
            <x-alerts.message :message="session('success')" />
            <x-utilities.table-basic id="careOfDatatable" class="display responsive nowrap" style="width:100%">
                <x-utilities.table-basic-head class="bg-info">
                    <tr>
                        <th>{{ __('SL') }}</th>
						<th>{{ __('Care Name') }}</th>
                        <th>{{ __('Code') }}</th>
                        <th>{{ __('Service Charge') }}</th>
                        <th>{{ __('Discount Percent') }}</th>
                        <th>{{ __('Discount Amount') }}</th>

                        <th>{{ __('Actions' )}}</th>
                    </tr>
                </x-utilities.table-basic-head>
                <x-utilities.table-basic-body>
                    @foreach ($careOfs as $careOf)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
						<td>{{ $careOf->care_name }}</td>
                        <td>{{ $careOf->code }}</td>
                        <td>{{ $careOf->service_charge }}</td>
                        <td>{{ $careOf->discount_percent }}</td>
                        <td>{{ $careOf->discount_amount }}</td>

                        <td class="d-flex justify-content-center">
                            <x-utilities.link-show href="{{route('care-ofs.show', $careOf->uuid)}}">{{ __('Show') }}</x-utilities.link-show>
                        
                            <x-utilities.link-edit href="{{route('care-ofs.edit', $careOf->uuid)}}">{{ __('Edit') }}</x-utilities.link-edit>
                        
                            <form style="display:inline" action="{{route('care-ofs.destroy', $careOf->uuid)}}" method="post">
                            @csrf
                            @method('delete')
                                <x-forms.button class="btn btn-danger" onClick="return confirm('Are you sure want to delete ?')" type="submit">{{ __('Delete') }}</x-forms.button> 
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </x-utilities.table-basic-body>
            </x-utilities.table-basic>
        </x-slot>
        <x-slot name="footer" class="d-flex">
			<div></div>
			<div>
				<x-utilities.link-create href="{{route('care-ofs.create')}}"><i class="fa fa-plus"></i> {{ __('Add New') }}</x-utilities.link-create>
			</div>
			<div></div>
		</x-slot>
    </x-utilities.card>

@push('css')
{{--pagespecific-css--}}
<link href="{{ asset('ui') }}/css/jquery.dataTables.min.css" rel="stylesheet" >
<link href="{{ asset('ui') }}/css/responsive.dataTables.min.css" rel="stylesheet" >
<link href="{{ asset('ui') }}/css/buttons.dataTables.min.css" rel="stylesheet" >
@endpush

@push('js')
{{--pagespecific-js--}}
<script src="ui/js/jquery.dataTables.min.js"></script>
<script src="ui/js/dataTables.responsive.min.js"></script>
<script src="ui/js/dataTables.buttons.min.js"></script>
<script src="ui/js/buttons.colVis.min.js"></script>

<script>
   $(document).ready(function() {
    $('#careOfDatatable').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'colvis'
        ]
    } );
  } );
</script>
@endpush

</x-masterdata-master>

masterdata/src/resources/views/care-ofs/show.blade.php
<x-masterdata-master>
    <x-utilities.card>
        <x-slot name="heading">
            {{ __('Care Of') }}
        </x-slot>
        <x-slot name="body">
       
			<p><b>{{ __('Care Name') }} : </b> {{ $careOf->care_name }}</p>
            <p><b>{{ __('Code') }} : </b> {{ $careOf->code }}</p>
            <p><b>{{ __('Service Charge') }} : </b> {{ $careOf->service_charge }}</p>
            <p><b>{{ __('Discount Percent') }} : </b> {{ $careOf->discount_percent }}</p>
            <p><b>{{ __('Discount Amount') }} : </b> {{ $careOf->discount_amount }}</p>
			
            {{--othersInfo--}}
        </x-slot>
        <x-slot name="footer" class="d-flex">
			<div></div>
			<div>
				<x-utilities.link-list href="{{route('care-ofs.index')}}"><i class="fa fa-list"></i> {{ __('List') }}</x-utilities.link-list>
			</div>
			<div></div>
		</x-slot>
    </x-utilities.card>
    
@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush
</x-masterdata-master>